### ISSUE TITLE
System did not attempt to deliver a bundle message to a Registered Webhook

### ISSUE THREAD

**Issue by AngryRoleplayer** [cswendrowski/HumbleBundleBot#5]
Does not post anything with proper registered webhooks and such

**Comment by cswendrowski** [comment]
In our Discord we got a new bundle just last night: 
![image](https://user-images.githubusercontent.com/15639841/58197953-fd678480-7c92-11e9-84a7-d724500576ac.png)

Can you give some more info on what you're experiencing? When is the last time you received a bundle? What bundle types are you registered for?

If you don't mind sharing, having your Webhook URL would be useful in looking into this. Feel free to join our support Discord in order to privately share the URL https://discord.gg/A7NBpcC

**Comment by cswendrowski** [comment]
Debug note: Webhook was registered as Games, ShouldRecieveUpdates true, WebhookType 0, Partner url present

**Comment by cswendrowski** [comment]
This has now been resolved!
